# Generated by Django 4.2.1 on 2023-08-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
